# Generated by Django 4.1.7 on 2023-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_alter_anime_aired_alter_anime_episodes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='img_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='ranked',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='score',
            field=models.FloatField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='synopsis',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
